allowBuilds:
  "@google/genai": false
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false

minimumReleaseAgeExclude:
  - "@oh-my-pi/omptype@18.2.5"
  - "@oh-my-pi/pi-ai@18.2.5"
  - "@oh-my-pi/pi-coding-agent@18.2.5"
  - "oxlint-tsgolint@7.0.2002"
  - "@oh-my-pi/omp-stats@18.2.5"
  - "@oh-my-pi/pi-agent-core@18.2.5"
  - "@oh-my-pi/pi-catalog@18.2.5"
  - "@oh-my-pi/pi-mnemopi@18.2.5"
  - "@oh-my-pi/pi-natives-darwin-arm64@18.2.5"
  - "@oh-my-pi/pi-natives-darwin-x64@18.2.5"
  - "@oh-my-pi/pi-natives-linux-arm64@18.2.5"
  - "@oh-my-pi/pi-natives-linux-x64@18.2.5"
  - "@oh-my-pi/pi-natives-win32-arm64@18.2.5"
  - "@oh-my-pi/pi-natives-win32-x64@18.2.5"
  - "@oh-my-pi/pi-natives@18.2.5"
  - "@oh-my-pi/pi-tui@18.2.5"
  - "@oh-my-pi/pi-utils@18.2.5"
  - "@oh-my-pi/pi-wire@18.2.5"
  - "@oh-my-pi/snapcompact@18.2.5"
  - "@oxlint-tsgolint/darwin-arm64@7.0.2002"
  - "@oxlint-tsgolint/darwin-x64@7.0.2002"
  - "@oxlint-tsgolint/linux-arm64@7.0.2002"
  - "@oxlint-tsgolint/linux-x64@7.0.2002"
  - "@oxlint-tsgolint/win32-arm64@7.0.2002"
  - "@oxlint-tsgolint/win32-x64@7.0.2002"
