packages:
  - .

shamefullyHoist: true

allowBuilds:
  better-sqlite3: true
  esbuild: true
  workerd: true
  vue-demi: true

minimumReleaseAgeExclude:
  - "wrangler@4.134.0"
  - miniflare@5.20260917.0-alpha
