import { randomUUID } from "node:crypto";
import {
  lstatSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  readlinkSync,
  renameSync,
  rmdirSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { createRequire } from "node:module";
import { basename, dirname, extname, isAbsolute, join, relative, resolve } from "node:path";
import { moveFile } from "./agents-sync.ts";
import type { Harness } from "./harness.ts";
import { agntnDataDir } from "./resolve.ts";
import type { PromptTemplateSyncTarget, ResolveOptions } from "./types.ts";

const GENERATED_MARKER = "# Generated by @agntn/harnesses from ";
const PORTABLE_PROMPT_NAME = /^[A-Za-z0-9][A-Za-z0-9_-]*$/u;

export type PromptSyncAction =
  | "linked"
  | "generated"
  | "relinked"
  | "replaced"
  | "adopted"
  | "removed"
  | "unchanged"
  | "skipped";

/** One prompt template's outcome at a harness destination. */
export interface PromptTemplateTargetResult {
  readonly name: string;
  readonly source?: string;
  readonly path: string;
  readonly action: PromptSyncAction;
  /** Backup path, skip reason, or a check-mode note. */
  readonly detail?: string;
}

/** One harness's outcome of a prompt template sync run. */
export interface PromptSyncTargetResult {
  readonly id: string;
  readonly path?: string;
  readonly format?: PromptTemplateSyncTarget["format"];
  /** Outcome for a Markdown destination, which is one link to the whole source directory. */
  readonly action?: PromptSyncAction;
  /** Backup path, skip reason, or a check-mode note. */
  readonly detail?: string;
  readonly templates: readonly PromptTemplateTargetResult[];
}

/** Outcome of one prompt template sync run. */
export interface PromptSyncReport {
  readonly source: string;
  readonly check: boolean;
  readonly templates: readonly string[];
  readonly targets: readonly PromptSyncTargetResult[];
}

interface PromptTemplate {
  readonly name: string;
  readonly path: string;
  readonly content: string;
  readonly gemini?: string;
}

type DestinationState =
  | { readonly kind: "missing" }
  | { readonly kind: "owned-file"; readonly content: string }
  | { readonly kind: "unmanaged-file" }
  | { readonly kind: "unsupported" };

const GEMINI_ACTION: Record<DestinationState["kind"], PromptSyncAction> = {
  missing: "generated",
  "owned-file": "replaced",
  "unmanaged-file": "adopted",
  unsupported: "skipped",
};

const GEMINI_BACKUP: Record<DestinationState["kind"], boolean> = {
  missing: false,
  "owned-file": true,
  "unmanaged-file": true,
  unsupported: false,
};

function readTemplates(sourceDir: string, check: boolean): PromptTemplate[] {
  let entries;
  try {
    entries = readdirSync(sourceDir, { withFileTypes: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    if (!check) mkdirSync(sourceDir, { recursive: true });
    return [];
  }

  const templates = entries
    .filter(
      (entry) =>
        (entry.isFile() || entry.isSymbolicLink()) && extname(entry.name).toLowerCase() === ".md",
    )
    .map((entry) => {
      const name = basename(entry.name, extname(entry.name));
      if (!PORTABLE_PROMPT_NAME.test(name)) {
        throw new TypeError(`Invalid prompt template filename: ${entry.name}`);
      }
      const path = join(sourceDir, entry.name);
      return {
        name,
        path,
        content: readFileSync(path, "utf8"),
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));

  const names = templates.map((template) => template.name.toLowerCase());
  if (new Set(names).size !== names.length) {
    throw new Error(`Duplicate prompt template names in ${sourceDir}`);
  }
  return templates;
}

function generatedSource(content: string): string | null {
  const firstLine = content.split("\n", 1)[0] ?? "";
  if (!firstLine.startsWith(GENERATED_MARKER)) return null;
  try {
    const source: unknown = JSON.parse(firstLine.slice(GENERATED_MARKER.length));
    return typeof source === "string" ? source : null;
  } catch {
    return null;
  }
}

function linkTarget(path: string): string {
  const target = readlinkSync(path);
  return isAbsolute(target) ? target : resolve(dirname(path), target);
}

function inspectDestination(path: string): DestinationState {
  let stats;
  try {
    stats = lstatSync(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return { kind: "missing" };
    throw error;
  }

  if (stats.isSymbolicLink()) return { kind: "unmanaged-file" };
  if (!stats.isFile()) return { kind: "unsupported" };

  const content = readFileSync(path, "utf8");
  if (generatedSource(content) !== null) return { kind: "owned-file", content };
  return { kind: "unmanaged-file" };
}

function tempPath(path: string, kind: string): string {
  return join(dirname(path), `.${basename(path)}-${randomUUID()}.${kind}.tmp`);
}

function linkDirectory(path: string, source: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temp = tempPath(path, "prompt-link");
  // Junctions let Windows link a directory without symlink privileges.
  symlinkSync(source, temp, "junction");
  renameSync(temp, path);
}

function writeTemplate(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temp = tempPath(path, "prompt-write");
  writeFileSync(temp, content);
  renameSync(temp, path);
}

function backupDestination(id: string, path: string, options: ResolveOptions): string {
  const backupDir = join(agntnDataDir(options), "diverged", "prompts", id);
  mkdirSync(backupDir, { recursive: true });
  const backup = join(backupDir, `${basename(path)}-${Date.now()}-${randomUUID()}`);
  if (lstatSync(path).isSymbolicLink()) {
    symlinkSync(linkTarget(path), backup);
    unlinkSync(path);
    return backup;
  }
  moveFile(path, backup);
  return backup;
}

function checkDetail(): string {
  return "check mode: not applied";
}

function isInsideDirectory(path: string, directory: string): boolean {
  const remainder = relative(directory, path);
  return remainder !== "" && !remainder.startsWith("..") && !isAbsolute(remainder);
}

function isLegacyTemplateLink(path: string, sourceDir: string): boolean {
  return lstatSync(path).isSymbolicLink() && isInsideDirectory(linkTarget(path), sourceDir);
}

type DirectoryState =
  | { readonly kind: "missing" | "correct-link" | "wrong-link" | "local-files" | "not-directory" }
  | { readonly kind: "legacy-links"; readonly entries: readonly string[] };

const DIRECTORY_ACTION: Record<DirectoryState["kind"], PromptSyncAction> = {
  missing: "linked",
  "correct-link": "unchanged",
  "wrong-link": "relinked",
  "legacy-links": "relinked",
  "local-files": "adopted",
  "not-directory": "skipped",
};

function inspectDirectory(targetDir: string, sourceDir: string): DirectoryState {
  let stats;
  try {
    stats = lstatSync(targetDir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return { kind: "missing" };
    throw error;
  }

  if (stats.isSymbolicLink()) {
    return { kind: linkTarget(targetDir) === sourceDir ? "correct-link" : "wrong-link" };
  }
  if (!stats.isDirectory()) return { kind: "not-directory" };

  // Per-template links from earlier releases carry nothing worth a backup.
  const entries = readdirSync(targetDir).map((entry) => join(targetDir, entry));
  return entries.every((entry) => isLegacyTemplateLink(entry, sourceDir))
    ? { kind: "legacy-links", entries }
    : { kind: "local-files" };
}

function clearDirectory(
  id: string,
  targetDir: string,
  state: DirectoryState,
  options: ResolveOptions,
): string | undefined {
  if (state.kind === "wrong-link" || state.kind === "local-files") {
    return backupDestination(id, targetDir, options);
  }
  if (state.kind === "legacy-links") {
    for (const entry of state.entries) unlinkSync(entry);
    rmdirSync(targetDir);
  }
  return undefined;
}

// A Markdown destination becomes one link to the whole source directory, so a
// template any harness adds or edits lands in the shared source.
function syncMarkdownDirectory(
  id: string,
  targetDir: string,
  sourceDir: string,
  check: boolean,
  options: ResolveOptions,
): Pick<PromptSyncTargetResult, "action" | "detail"> {
  const state = inspectDirectory(targetDir, sourceDir);
  const action = DIRECTORY_ACTION[state.kind];
  if (state.kind === "correct-link") return { action };
  if (state.kind === "not-directory") {
    return { action, detail: "destination exists and is not a directory or symlink" };
  }
  if (check) return { action, detail: checkDetail() };

  const detail = clearDirectory(id, targetDir, state, options);
  linkDirectory(targetDir, sourceDir);
  return { action, detail };
}

// yaml is most of the modules a package import loads, and only Gemini's
// frontmatter needs it. A lazy require keeps the sync API synchronous.
function parseYaml(raw: string): unknown {
  const load = createRequire(import.meta.url);
  const yaml = load("yaml") as typeof import("yaml");
  return yaml.parse(raw);
}

function frontmatterDescription(raw: string, path: string): string | undefined {
  const frontmatter: unknown = parseYaml(raw);
  if (frontmatter === null) return undefined;
  if (typeof frontmatter !== "object" || Array.isArray(frontmatter)) {
    throw new TypeError(`Prompt template frontmatter is not an object: ${path}`);
  }
  const description = (frontmatter as Record<string, unknown>).description;
  if (description !== undefined && typeof description !== "string") {
    throw new TypeError(`Prompt template description is not a string: ${path}`);
  }
  return description;
}

function parseMarkdownTemplate(template: PromptTemplate): {
  readonly description?: string;
  readonly prompt: string;
} {
  const match = /^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/.exec(template.content);
  if (match === null) return { prompt: template.content.replaceAll("$ARGUMENTS", "{{args}}") };

  const description = frontmatterDescription(match[1] ?? "", template.path);
  return {
    ...(description === undefined ? {} : { description }),
    prompt: template.content.slice(match[0].length).replaceAll("$ARGUMENTS", "{{args}}"),
  };
}
function geminiContent(template: PromptTemplate): string {
  const parsed = parseMarkdownTemplate(template);
  const fields = [
    `${GENERATED_MARKER}${JSON.stringify(template.path)}`,
    ...(parsed.description === undefined
      ? []
      : [`description = ${JSON.stringify(parsed.description)}`]),
    `prompt = ${JSON.stringify(parsed.prompt)}`,
    "",
  ];
  return fields.join("\n");
}

function syncGeminiTemplate(
  id: string,
  targetDir: string,
  template: PromptTemplate,
  check: boolean,
  options: ResolveOptions,
): PromptTemplateTargetResult {
  const path = join(targetDir, `${template.name}.toml`);
  const content = template.gemini ?? geminiContent(template);
  const state = inspectDestination(path);
  if (state.kind === "owned-file" && state.content === content) {
    return { name: template.name, source: template.path, path, action: "unchanged" };
  }
  if (state.kind === "unsupported") {
    return {
      name: template.name,
      source: template.path,
      path,
      action: "skipped",
      detail: "destination exists and is not a file or symlink",
    };
  }

  const action = GEMINI_ACTION[state.kind];
  if (check) {
    return { name: template.name, source: template.path, path, action, detail: checkDetail() };
  }

  let detail: string | undefined;
  if (GEMINI_BACKUP[state.kind]) detail = backupDestination(id, path, options);
  writeTemplate(path, content);
  return { name: template.name, source: template.path, path, action, detail };
}

function staleGeminiSource(path: string, sourceDir: string): string | null {
  let content: string;
  try {
    content = readFileSync(path, "utf8");
  } catch {
    return null;
  }
  const source = generatedSource(content);
  if (source === null) return null;
  return isInsideDirectory(source, sourceDir) ? source : null;
}

// The Gemini directory keeps only commands generated from the source. Stale
// generated files are deleted; anything else is moved to a backup.
function pruneGeminiTarget(
  id: string,
  targetDir: string,
  sourceDir: string,
  activeNames: ReadonlySet<string>,
  check: boolean,
  options: ResolveOptions,
): PromptTemplateTargetResult[] {
  let entries;
  try {
    entries = readdirSync(targetDir);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return [];
    throw error;
  }

  return entries
    .filter((entry) => !activeNames.has(entry))
    .map((entry): PromptTemplateTargetResult => {
      const path = join(targetDir, entry);
      const name = basename(entry, extname(entry));
      const source = staleGeminiSource(path, sourceDir);
      if (check) {
        return {
          name,
          ...(source === null ? {} : { source }),
          path,
          action: "removed",
          detail: checkDetail(),
        };
      }
      if (source !== null) {
        unlinkSync(path);
        return { name, source, path, action: "removed" };
      }
      return { name, path, action: "removed", detail: backupDestination(id, path, options) };
    });
}

function syncTarget(
  harness: Harness,
  templates: readonly PromptTemplate[],
  sourceDir: string,
  check: boolean,
  options: ResolveOptions,
): PromptSyncTargetResult {
  const target = harness.promptTemplateSyncTarget;
  if (target === null) {
    return {
      id: harness.id,
      detail: "no stable user-scope prompt template destination",
      templates: [],
    };
  }

  const resolved = harness.resolveCandidates([target], options)[0];
  if (resolved === undefined) {
    return {
      id: harness.id,
      detail: "prompt template destination is unavailable on this platform",
      templates: [],
    };
  }
  // Registry paths end in a separator, which a directory symlink cannot carry.
  const targetDir = resolve(resolved.path);
  if (resolved.format === "markdown") {
    return {
      id: harness.id,
      path: targetDir,
      format: resolved.format,
      ...syncMarkdownDirectory(harness.id, targetDir, sourceDir, check, options),
      templates: [],
    };
  }

  const results = templates.map((template) =>
    syncGeminiTemplate(harness.id, targetDir, template, check, options),
  );
  const activeNames = new Set(templates.map((template) => `${template.name}.toml`));
  results.push(...pruneGeminiTarget(harness.id, targetDir, sourceDir, activeNames, check, options));
  return {
    id: harness.id,
    path: targetDir,
    format: resolved.format,
    templates: results,
  };
}

/**
 * Synchronizes canonical Markdown prompt templates into each harness's stable
 * user-scope destination. A Markdown harness's destination becomes one symlink
 * to the source directory; Gemini's directory holds only TOML commands
 * generated from it. Anything else found there is backed up first. In check
 * mode nothing is written.
 *
 * @param harnesses - Harnesses to inspect or update.
 * @param check - Report intended changes without writing them.
 * @param options - Path-resolution overrides.
 * @returns {PromptSyncReport} Per-harness synchronization outcomes.
 */
export function syncPromptTemplates(
  harnesses: readonly Harness[],
  check = false,
  options: ResolveOptions = {},
): PromptSyncReport {
  const source = join(agntnDataDir(options), "prompts");
  const templates = readTemplates(source, check);
  const prepared = harnesses.some(
    (harness) => harness.promptTemplateSyncTarget?.format === "gemini-toml",
  )
    ? templates.map((template) => ({ ...template, gemini: geminiContent(template) }))
    : templates;
  return {
    source,
    check,
    templates: prepared.map((template) => template.name),
    targets: harnesses.map((harness) => syncTarget(harness, prepared, source, check, options)),
  };
}
